[package]
name = "day-10"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10"
indicatif = { version = "0.17", features = ["rayon"] }
good_lp = { version = "1.14", default-features = false, features = ["highs"] }
